name: flutter_iniciante_widgets
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  flutter_launcher_icons: ^0.9.0
  #multilevel_drawer: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/logosalao.png"
  android: "launcher_icon"
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/salaoilka.png
   - assets/images/novafrente.png
   - assets/images/novafrente.jpg
   - assets/images/logosalao.png
   - assets/images/Splash_screen.png
   - assets/images/logosalao2.png
   - assets/images/salaodebeleza.jpg
   - assets/images/agenda.svg
   - assets/icons/icons svg/livro-de-endereços.svg
   - assets/images/bitmap.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
        - asset: fonts/MyFlutterApp_.ttf
        - asset: fonts/SilverFlower.ttf
  #         style: italic

    - family: Italianno
      fonts:
        - asset: fonts/Italianno/Italianno-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
    - family: Playball
      fonts:
        - asset: fonts/Playball/Playball-Regular.ttf

    - family: Kaushan_Script
      fonts:
        - asset: fonts/Kaushan_Script/KaushanScript-Regular.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Black.ttf
        - asset: fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
        - asset: fonts/Roboto/Roboto-Light.ttf
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
        - asset: fonts/Roboto/Roboto-Medium.ttf
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Thin.ttf
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf

    - family: Pinyon_Script
      fonts:
        - asset: fonts/Pinyon_Script/PinyonScript-Regular.ttf

    - family: Big_Shoulders_Inline_Text
      fonts:
        - asset: fonts/Big_Shoulders_Inline_Text/BigShouldersInlineText-Black.ttf
        - asset: fonts/Big_Shoulders_Inline_Text/BigShouldersInlineText-Bold.ttf
        - asset: fonts/Big_Shoulders_Inline_Text/BigShouldersInlineText-ExtraBold.ttf
        - asset: fonts/Big_Shoulders_Inline_Text/BigShouldersInlineText-Light.ttf
        - asset: fonts/Big_Shoulders_Inline_Text/BigShouldersInlineText-Medium.ttf
        - asset: fonts/Big_Shoulders_Inline_Text/BigShouldersInlineText-Regular.ttf
        - asset: fonts/Big_Shoulders_Inline_Text/BigShouldersInlineText-SemiBold.ttf
        - asset: fonts/Big_Shoulders_Inline_Text/BigShouldersInlineText-Thin.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
